<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr class="bgcolor_0099AA">
    <td width="25"><img src="/education/heroesvillains/images/pixels/hextrans.gif" alt="" width="25" height="10" /></td>
    <td width="100%" align="left" valign="top"><img src="/education/heroesvillains/images/pixels/hextrans.gif" alt="" width="730" height="10" /></td>
    <td width="25"><img src="/education/heroesvillains/images/pixels/hextrans.gif" alt="" width="25" height="10" /></td>
  </tr>
  <tr  class="hv_footer">
    <td width="25">&nbsp;</td>
    <td width="100%" align="left" valign="top"><a href="/contact/" class="footer_text">Contact us</a> 
        | <a href="/education/heroesvillains/credits/" class="footer_text">Credits</a> | <a href="/education/heroesvillains/sitemap/" class="footer_text">Site map</a> | <a class="footer_text" href="/education/heroesvillains/glossary/" onclick="PRO_openPopupWindow('/education/heroesvillains/glossary/','lcpop','620','500','scrollbars=yes,resizable=yes','yes');return document.MM_returnValue">Glossary</a> |  <a href="/education/heroesvillains/teachers/" class="footer_text">Teacher's notes</a></td>
    <td width="25">&nbsp;</td>
  </tr>
  <tr class="bgcolor_0099AA">
    <td width="25"><img src="/education/heroesvillains/images/pixels/hextrans.gif" alt="" width="25" height="10" /></td>
    <td width="100%" align="left" valign="top"><img src="/education/heroesvillains/images/pixels/hextrans.gif" alt="" width="730" height="10" /></td>
    <td width="25"><img src="/education/heroesvillains/images/pixels/hextrans.gif" alt="" width="25" height="10" /></td>
  </tr>
</table>