<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="15"><img src="/education/heroesvillains/images/pixels/hextrans.gif" alt="" width="8" height="15" /></td>
    <td align="right" valign="top" class="hv_bodylink"><a href="#top" class="bodylink_text">Top of Page</a> 
        | <a href="#" class="bodylink_text" onclick="lc_print()" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('print','','/education/heroesvillains/images/buttons/hv_print_d.gif',1)">Print</a> | <a href="javascript:window.close();" class="bodylink_text">Close</a></td>
    <td width="15"><img src="/education/heroesvillains/images/pixels/hextrans.gif" alt="" width="15" height="15" /></td>
  </tr>
    <tr>
    <td width="15"><img src="/education/heroesvillains/images/pixels/hextrans.gif" alt="" width="15" height="10" /></td>
    <td><img src="/education/heroesvillains/images/pixels/hextrans.gif" alt="" width="15" height="10" /></td>
    <td width="15"><img src="/education/heroesvillains/images/pixels/hextrans.gif" alt="" width="15" height="10" /></td>
  </tr>
</table>