<meta name="DC.title" content="The National Archives Learning Curve | Heroes & Villains | Mussolini & Abyssinia | Why invade Abyssinia?" />
<meta name="DC.subject" content="history, transcript, source, evidence, document, photo, photograph, poster, letter, telegram, message, map, speech, Haile, Selassie, Addis Ababa, Abyssinia, Ethiopia, Italy, Mussolini, empire, Africa, army, Fascist, fascism, league, nations" />
<meta name="keywords" content="history, transcript, source, evidence, document, photo, photograph, poster, letter, telegram, message, map, speech, Haile, Selassie, Addis Ababa, Abyssinia, Ethiopia, Italy, Mussolini, empire, Africa, army, Fascist, fascism, league, nations"/>
<meta name="DCTERMS.temporal" content="1919-1936" />
<meta name="DC.description" content="In this case study you will use original documents to investigate why Mussolini invaded Abyssinia. For key stage 3-5 (age 11-18)"/>
<meta name="description" content="In this case study you will use original documents to investigate why Mussolini invaded Abyssinia. For key stage 3-5 (age 11-18)"/>

