<meta name="DC.title" content="The National Archives Learning Curve | Heroes & Villains | Truman & the atomic bomb | Firebombing" />
<meta name="DC.subject" content="history, transcript, source, evidence, document, photo, photograph, message, map, fire, bombing, bomb, firebombing, firebomb, Japan, Japanese, morale, military, surrender, USA, Tokyo, Allies, Allied, strategy, damage, Yokohama, Nagoya, Osaka, Kobe" />
<meta name="keywords" content="history, transcript, source, evidence, document, photo, photograph, message, map, fire, bombing, bomb, firebombing, firebomb, Japan, Japanese, morale, military, surrender, USA, Tokyo, Allies, Allied, strategy, damage, Yokohama, Nagoya, Osaka, Kobe"/>
<meta name="DCTERMS.temporal" content="1939-1949" />
<meta name="DC.description" content="In this case study you will use original documents to examine why the firebombing did not lead Japan to surrender.  For key stage 3-5 (age 11-18)"/>
<meta name="description" content="In this case study you will use original documents to examine why the firebombing did not lead Japan to surrender.  For key stage 3-5 (age 11-18)"/>
